<?php

declare(strict_types=1);
namespace TreesListModule;
use Fisharebest\Webtrees\Http\RequestHandlers\TreePage;
use Fisharebest\Webtrees\I18N;

?>
<style>
    .p-1:hover {  
  /* 鼠标悬停时的背景颜色和字体颜色 */  
  background-color: #888; /* 黑色背景 */  
  color: #fff; /* 白色字体 */  
</style>

        <?php foreach ($all_trees as $tree ) : ?>
            <div class="d-flex mb-2 border rounded">
                <div class="p-2 flex-grow-1 ">
                    <a href="<? echo e(route(TreePage::class,['tree'=>$tree->name()])); ?>">
                    <b><?= e($tree->title()) ?></b></a>
                </div>
                <div id="navbar" class="p-1 border border-top-0 border-bottom-0" title="<?php echo I18N::translate("Families"); ?>">
                    
                    <?= I18N::number(intval($families[$tree->id()])) ?>
                </div>
                <div id="navbar" class="p-1" title="<?php echo I18N::translate("Individuals"); ?>">
                    
                    <?=  I18N::number(intval($individuals[$tree->id()])) ?>
                </div>
				<div id="navbar" class="p-1 border border-top-0 border-bottom-0" title="<?php echo I18N::translate("Surnames"); ?>">
				    
                    <?=  I18N::number(intval($surnames[$tree->id()])) ?>
                </div>
                <div id="navbar" class="p-1" title="<?php echo I18N::translate("Events"); ?>">
                    
				    <?=  I18N::number(intval($events[$tree->id()])) ?>
                </div>
				
            </div>
        <?php endforeach ?>
